name: base            
dependencies:         # everything under this, installed by conda
- Keras
- Pillow
- requests
- pytest
- numpy
# - tensorflow
- pip:                # everything under this, installed by pip
  - cachetools   
  - /root/tensorflow/pip/tensorflow_pkg/tensorflow-1.9.0-cp36-cp36m-linux_x86_64.whl